const joi = require('joi');
module.exports = {
    id: joi.number().integer().min(1),
    branchId: joi.number().integer().min(1),
    roleId: joi.number().integer().min(1),
    companyId: joi.number().integer().min(1),
    productId: joi.number().integer().min(1),
    categoryId: joi.number().integer().min(1),
    userId: joi.number().integer().min(1),
    customerId: joi.number().integer().min(1),
    providerId: joi.number().integer().min(1),
    purchaseId: joi.number().integer().min(1),

    permissions: joi.string().valid('A', 'B', 'C', 'D', 'Z'),
    type: joi.string().valid('REEMBOLSO', 'CAMBIO DE PRODUCTO', 'CAMBIO POR BONO'),
    reason: joi.string(),
    refund_number: joi.string(),
    customer_email: joi.string().email(),
    payment_method: joi.string().valid('TRANSFERENCIA', 'EFECTIVO', 'ECOMMERCE'),
    invoice_number: joi.string(),
    color: joi.string(),
    description: joi.string(),
    size: joi.string(),
    brand: joi.string(),
    price: joi.number(),
    refer_id: joi.string(),
    status: joi.string().valid("EN ESPERA", "CONFIRMADO", "ENTREGADO"),
    bill_reference: joi.string(),
    URL: joi.string().uri(),
    alternative_text: joi.string(),
    holder: joi.string(),
    NIT: joi.string(),
    bank_account_type: joi.string().valid("CORRIENTES", "AHORROS"),
    social_reason: joi.string(),
    bank: joi.string(),
    bank_account_number: joi.string(),
    email: joi.string().email(),
    phone: joi.string().min(10).max(15),
    password: joi.string(),
    name: joi.string(),
    last_name: joi.string(),
    active: joi.forbidden(),
    direction: joi.string(),
    city: joi.string(),
};